---
title: Aaron Aiken
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@aaronaiken.me
description: |
  Welcome to the personal website and blog of Aaron Aiken. This website will include ramblings related to business, being an entrepreneur, running online businesses, learning, teaching, cigars, coffee, travel, family, technology, and everything in-between.
baseurl: 
url: http://aaronaiken.me
twitter_username: aaron_aiken
github_username: aaronaiken
markdown: kramdown
