# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aaron Aiken
email: hello@aaronaiken.me
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the personal website and blog of Aaron Aiken. This website will include ramblings related to business, being an entrepreneur, running online businesses, learning, teaching, cigars, coffee, travel, family, technology, and everything in-between.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aaronaiken.me" # the base hostname & protocol for your site
twitter_username: aaron_aiken
github_username:  

# Build settings
markdown: kramdown
